### ISSUE TITLE
Is FullStory implemented in it

### ISSUE THREAD

**Issue by ahmadsyed** [fullstorydev/react-native-shoppe-demo#5]
Hi @sabrina-li , 
I searched the whole project to find any mention of FullStory But was not able to find it. Am I missing anything here?

**Comment by sabrina-li** [comment]
Hi @ahmadsyed Thank you for your interest! This project is still under development and we will have it fully integrated soon! I have opened #6 to clarify this. Stay tuned!

**Comment by sabrina-li** [comment]
hi @ahmadsyed we've merged https://github.com/fullstorydev/react-native-shoppe-demo/pull/7 to add FullStory to the app. Feel free to try it out, and here is a [guide doc](https://help.fullstory.com/hc/en-us/articles/360052419133-Getting-Started-with-FullStory-React-Native-Recording), in case you haven't seen it. If you have any further questions please feel free to reach out to our support team at mobile-support@fullstory.com and our team would be happy to assist
Thank you!
